/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Conversations": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DirectApiSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DiscordPublicKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubAppId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubPrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ProcessedEvents": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SlackBotToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SlackSigningSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}