/**
 * Writes deterministic generated resource references for app code.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { CliManifest, GeneratedIds } from "./contracts.ts";
import { GENERATED_DIR, PROJECT_DIR } from "./config.ts";
import type { ResourceAliases } from "./manifest.ts";
import type { CompiledChannel } from "./manifest.ts";

/**
 * The environment's deployment endpoint, used to embed the scoped invoke URL
 * (`/v1/{projectSlug}/agents/{environmentSlug}/{endpointId}`) into each generated
 * agent reference so the SDK posts to the same path the dashboard shows.
 */
export type GeneratedEndpoint = {
  accountId: string;
  endpointId: string;
  projectSlug: string;
  environmentSlug: string;
} | null | undefined;

export async function writeGeneratedFiles(
  manifest: CliManifest,
  ids: GeneratedIds,
  cwd = process.cwd(),
  aliases: ResourceAliases = {},
  endpoint: GeneratedEndpoint = null,
  channels: CompiledChannel[] = [],
): Promise<void> {
  const dir = resolve(cwd, PROJECT_DIR, GENERATED_DIR);
  const scopedIds = idsForManifest(ids, manifest);
  await mkdir(dir, { recursive: true });
  await writeFile(resolve(dir, "ids.ts"), idsFile(scopedIds), "utf8");
  await writeFile(resolve(dir, "api.ts"), apiFile(manifest, scopedIds, aliases, endpoint, channels), "utf8");
  await writeFile(resolve(dir, "resources.ts"), resourcesFile(manifest), "utf8");
  await writeFile(resolve(dir, "dataModel.ts"), dataModelFile(), "utf8");
}

function idsForManifest(ids: GeneratedIds, manifest: CliManifest): GeneratedIds {
  const namesByKind = {
    agents: namesForKind(manifest, "agent"),
    workspaces: namesForKind(manifest, "workspace"),
    sandboxes: namesForKind(manifest, "sandbox"),
    crons: namesForKind(manifest, "cron"),
    skills: namesForKind(manifest, "skill"),
    tools: namesForKind(manifest, "tool"),
  };

  return {
    agents: pickIds(ids.agents, namesByKind.agents),
    workspaces: pickIds(ids.workspaces, namesByKind.workspaces),
    sandboxes: pickIds(ids.sandboxes, namesByKind.sandboxes),
    crons: pickIds(ids.crons, namesByKind.crons),
    skills: pickIds(ids.skills, namesByKind.skills),
    tools: pickIds(ids.tools, namesByKind.tools),
  };
}

function namesForKind(manifest: CliManifest, kind: string): Set<string> {
  return new Set(
    manifest.resources
      .filter((resource) => resource.kind === kind)
      .map((resource) => resource.name),
  );
}

function pickIds(values: Record<string, string>, names: Set<string>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(values).filter(([name]) => names.has(name)),
  );
}

function idsFile(ids: GeneratedIds): string {
  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `export const ids = ${JSON.stringify(ids, null, 2)} as const;\n` +
    `export const agents = ids.agents;\n` +
    `export const workspaces = ids.workspaces;\n` +
    `export const sandboxes = ids.sandboxes;\n` +
    `export const crons = ids.crons;\n` +
    `export const skills = ids.skills;\n` +
    `export const tools = ids.tools;\n`;
}

function resourcesFile(manifest: CliManifest): string {
  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `export const manifest = ${JSON.stringify(manifest, null, 2)} as const;\n`;
}

function apiFile(
  manifest: CliManifest,
  ids: GeneratedIds,
  aliases: ResourceAliases,
  endpoint: GeneratedEndpoint,
  channels: CompiledChannel[],
): string {
  const agents = Object.keys(ids.agents);
  // When the environment has a runtime key, embed its authoritative slugs +
  // endpointId so the SDK posts to the scoped /v1 URL the dashboard advertises.
  const scope = endpoint
    ? `, endpointId: ${JSON.stringify(endpoint.endpointId)}, projectSlug: ${JSON.stringify(endpoint.projectSlug)}, environmentSlug: ${JSON.stringify(endpoint.environmentSlug)}`
    : "";
  const agentEntries = agents.map((name) =>
    `    ${propertyKey(aliases.agent?.[name] ?? name)}: { kind: "agent", name: ${JSON.stringify(name)}, id: ids.agents[${JSON.stringify(name)}], project: ${JSON.stringify(manifest.project)}, environment: ${JSON.stringify(manifest.environment)}${scope} },`,
  ).join("\n");
  const channelEntries = endpoint
    ? channels.map((channel) => {
      const path = `/webhooks/${encodeURIComponent(endpoint.accountId)}/${encodeURIComponent(ids.agents[channel.agentName] ?? channel.agentName)}/${encodeURIComponent(channel.type)}`;
      return `    ${propertyKey(channel.alias)}: { kind: "channel", type: ${JSON.stringify(channel.type)}, agentName: ${JSON.stringify(channel.agentName)}, agentId: ids.agents[${JSON.stringify(channel.agentName)}], accountId: ${JSON.stringify(endpoint.accountId)}, webhookPath: ${JSON.stringify(path)} },`;
    }).join("\n")
    : "";

  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `import type { ResourceApi } from "filthy-panty";\n` +
    `import { ids } from "./ids";\n\n` +
    `/** Typed references for resources defined in filthypanty/. */\n` +
    `export const api = {\n` +
    `  agents: {\n${agentEntries}\n  },\n` +
    `  channels: {\n${channelEntries}\n  },\n` +
    `  workspaces: ${aliasedIdMap("workspaces", ids.workspaces, aliases.workspace)},\n` +
    `  sandboxes: ${aliasedIdMap("sandboxes", ids.sandboxes, aliases.sandbox)},\n` +
    `  crons: ${aliasedIdMap("crons", ids.crons, aliases.cron)},\n` +
    `  skills: ${aliasedIdMap("skills", ids.skills, aliases.skill)},\n` +
    `  tools: ${aliasedIdMap("tools", ids.tools, aliases.tool)},\n` +
    `} as const satisfies ResourceApi;\n`;
}

/**
 * Renders an `{ alias: ids.<idsKey>[name], ... }` block keyed by each resource's
 * exported variable name (falling back to its resource name), mirroring how agent
 * references are keyed so app code uses dot access instead of bracket lookups.
 * The api property may differ from the ids key (e.g. `crons` reads `ids.crons`,
 * which mirrors the server's deploy-response contract).
 */
function aliasedIdMap(idsKey: string, values: Record<string, string>, alias: Record<string, string> | undefined): string {
  const names = Object.keys(values);
  if (names.length === 0) return "{}";
  const entries = names.map((name) =>
    `    ${propertyKey(alias?.[name] ?? name)}: ids.${idsKey}[${JSON.stringify(name)}],`,
  ).join("\n");

  return `{\n${entries}\n  }`;
}

function propertyKey(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function dataModelFile(): string {
  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `export type { AgentReference, ChannelReference, AgentRunInput, AgentRunResult, ResourceApi } from "filthy-panty";\n`;
}
