/**
 * Writes deterministic generated resource references for app code.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { CliManifest, GeneratedIds } from "./contracts.ts";
import { GENERATED_DIR, PROJECT_DIR } from "./config.ts";
import type { ResourceAliases } from "./manifest.ts";

export async function writeGeneratedFiles(
  manifest: CliManifest,
  ids: GeneratedIds,
  cwd = process.cwd(),
  aliases: ResourceAliases = {},
): Promise<void> {
  const dir = resolve(cwd, PROJECT_DIR, GENERATED_DIR);
  const scopedIds = idsForManifest(ids, manifest);
  await mkdir(dir, { recursive: true });
  await writeFile(resolve(dir, "ids.ts"), idsFile(scopedIds), "utf8");
  await writeFile(resolve(dir, "api.ts"), apiFile(manifest, scopedIds, aliases), "utf8");
  await writeFile(resolve(dir, "resources.ts"), resourcesFile(manifest), "utf8");
  await writeFile(resolve(dir, "dataModel.ts"), dataModelFile(), "utf8");
}

function idsForManifest(ids: GeneratedIds, manifest: CliManifest): GeneratedIds {
  const namesByKind = {
    agents: namesForKind(manifest, "agent"),
    workspaces: namesForKind(manifest, "workspace"),
    sandboxes: namesForKind(manifest, "sandbox"),
    cronJobs: namesForKind(manifest, "cronJob"),
    skills: namesForKind(manifest, "skill"),
    tools: namesForKind(manifest, "tool"),
  };

  return {
    agents: pickIds(ids.agents, namesByKind.agents),
    workspaces: pickIds(ids.workspaces, namesByKind.workspaces),
    sandboxes: pickIds(ids.sandboxes, namesByKind.sandboxes),
    cronJobs: pickIds(ids.cronJobs, namesByKind.cronJobs),
    skills: pickIds(ids.skills, namesByKind.skills),
    tools: pickIds(ids.tools, namesByKind.tools),
  };
}

function namesForKind(manifest: CliManifest, kind: string): Set<string> {
  return new Set(
    manifest.resources
      .filter((resource) => resource.kind === kind)
      .map((resource) => resource.name),
  );
}

function pickIds(values: Record<string, string>, names: Set<string>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(values).filter(([name]) => names.has(name)),
  );
}

function idsFile(ids: GeneratedIds): string {
  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `export const ids = ${JSON.stringify(ids, null, 2)} as const;\n` +
    `export const agents = ids.agents;\n` +
    `export const workspaces = ids.workspaces;\n` +
    `export const sandboxes = ids.sandboxes;\n` +
    `export const cronJobs = ids.cronJobs;\n` +
    `export const skills = ids.skills;\n` +
    `export const tools = ids.tools;\n`;
}

function resourcesFile(manifest: CliManifest): string {
  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `export const manifest = ${JSON.stringify(manifest, null, 2)} as const;\n`;
}

function apiFile(manifest: CliManifest, ids: GeneratedIds, aliases: ResourceAliases): string {
  const agents = Object.keys(ids.agents);
  const agentEntries = agents.map((name) =>
    `    ${propertyKey(aliases.agent?.[name] ?? name)}: { kind: "agent", name: ${JSON.stringify(name)}, id: ids.agents[${JSON.stringify(name)}], project: ${JSON.stringify(manifest.project)}, environment: ${JSON.stringify(manifest.environment)} },`,
  ).join("\n");

  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `import type { ResourceApi } from "filthy-panty";\n` +
    `import { ids } from "./ids";\n\n` +
    `/** Typed references for resources defined in filthypanty/. */\n` +
    `export const api = {\n` +
    `  agents: {\n${agentEntries}\n  },\n` +
    `  workspaces: ids.workspaces,\n` +
    `  sandboxes: ids.sandboxes,\n` +
    `  cronJobs: ids.cronJobs,\n` +
    `  skills: ids.skills,\n` +
    `  tools: ids.tools,\n` +
    `} as const satisfies ResourceApi;\n`;
}

function propertyKey(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);
}

function dataModelFile(): string {
  return `// Generated by filthy-panty. Do not edit by hand.\n` +
    `export type { AgentReference, AgentRunInput, AgentRunResult, ResourceApi } from "filthy-panty";\n`;
}
