import { $ } from "bun";
import { access, readFile, readdir, writeFile } from "node:fs/promises";

const FUNCTIONS_DIR = new URL("../functions/", import.meta.url);
const SYSTEM_PROMPT_SOURCE = new URL("../SYSTEM.md", import.meta.url);
const SYSTEM_PROMPT_MODULE = new URL("../functions/_shared/generated-system-prompt.ts", import.meta.url);

const functionNames = await findFunctionNames();

await $`rm -rf dist`;
await syncSystemPromptModule();

if (functionNames.length === 0) {
  console.log("No function folders found. Add a bootstrap.ts under functions/<name>/.");
  process.exit(0);
}

for (const functionName of functionNames) {
  console.log(`Building ${functionName}...`);
  await $`bun build --compile --target bun-linux-arm64 ./functions/${functionName}/bootstrap.ts --outfile dist/${functionName}/bootstrap`;
}

console.log("All functions built successfully.");

async function syncSystemPromptModule() {
  const systemPrompt = await readFile(SYSTEM_PROMPT_SOURCE, "utf8");
  const moduleSource = `/**
 * Generated system prompt module.
 * Do not edit this file directly; update SYSTEM.md and rebuild instead.
 */

export const DEFAULT_SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)};
`;

  await writeFile(SYSTEM_PROMPT_MODULE, moduleSource);
}

async function findFunctionNames() {
  const entries = await readdir(FUNCTIONS_DIR, { withFileTypes: true });
  const names = await Promise.all(
    entries
      .filter((entry) => entry.isDirectory())
      .map(async (entry) => {
        try {
          await access(new URL(`${entry.name}/bootstrap.ts`, FUNCTIONS_DIR));
          return entry.name;
        } catch {
          return null;
        }
      }),
  );

  return names.filter((name): name is string => name !== null).sort();
}
