/**
 * CI helper to sync the embedded system prompt module with the source file.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";

const SYSTEM_PROMPT_SOURCE = new URL("../SYSTEM.md", import.meta.url);
const GENERATED_DIR = new URL("../functions/_shared/.generated/", import.meta.url);
const SYSTEM_PROMPT_MODULE = new URL("./system-prompt.ts", GENERATED_DIR);

export async function syncSystemPromptModule(): Promise<void> {
  const systemPrompt = await readFile(SYSTEM_PROMPT_SOURCE, "utf8");
  const moduleSource = `/**
 * Embedded system prompt generated from SYSTEM.md at build/dev/check time.
 * Do not edit this file directly.
 */

export const DEFAULT_SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)};
`;

  await mkdir(GENERATED_DIR, { recursive: true });
  await writeFile(SYSTEM_PROMPT_MODULE, moduleSource);
}

if (import.meta.main) {
  await syncSystemPromptModule();
}
