/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AccountConfigEncryptionSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AdminAccountSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KubernetesSandboxKubeconfig": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SandboxNetwork": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}